name: sb_payment_sdk
description: Official SB Payment SDK
version: 0.1.0
homepage: https://github.com/Startbutton-Engineering/payment-sdk-flutter.git

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^7.2.0
  http: ^1.0.0
  cached_network_image: ^3.1.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  flutter_screenutil: ^5.0.0+2
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  get: ^4.6.5
  circular_profile_avatar: ^2.0.5
  lottie: ^1.2.1
  image: ^4.3.0
  injectable: ^2.1.0
  dio: ^4.0.0
  route_animation_helper: ^2.0.0+7
  google_fonts: ^6.2.1
  swipeable_page_route: ^0.4.4
  intl_phone_field: ^3.2.0
  dropdown_button2: ^2.3.9
  shared_preferences: ^2.3.4
  fluttertoast: ^8.2.10
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: hkgrotesk
      fonts:
        - asset: assets/fonts/hk-grotesk.regular.otf

    - family: satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
